### PR TITLE
Add n

### PR DESCRIPTION
**Pull request by larmarange**
Exploratory and experimental PR

Not to be considered for merging at this stage

- [x] add tests for a wide range of models
- [x] integration in `tidy_plus_plus()`
- [x] finalize documentation
- [x] finalize examples in documentation
- [x] update vignette
- [x] update NEWS

### CODE REVIEW

**Comment by ddsjoberg** [comment]
> Dear @ddsjoberg
> 
> `tidy_add_n()` is ready for review if you want to test it.
> 
> Cheers

Awesome! I'll take a look!

**Comment by ddsjoberg** [comment]
@larmarange I've been playing around with this and it's perfect.  I'll do some more testing.  The only thing I would add is more details to the description `"Add the number of observations in a new column n taking into account interaction terms and the different types of contrasts."` I would add what numbers it adds for continuous, categorical, and dichotomous data.  What will be reported for various contrasts, etc.

**Comment by larmarange** [comment]
Dear @ddsjoberg 

I have developed the documentation of `tidy_add_n()`. I'm not sure if it is clear and I would appreciate an external look at it.

Best

**Comment by larmarange** [comment]
Small question: what should be the default value for `add_n` in `tidy_plus_plus()`? `TRUE` or `FALSE`? As it is not changing the structure of the results (just additional columns), it's maybe worth to be `TRUE` by default (for simplicity for final users)?

**Comment by ddsjoberg** [comment]
> Small question: what should be the default value for `add_n` in `tidy_plus_plus()`? `TRUE` or `FALSE`? As it is not changing the structure of the results (just additional columns), it's maybe worth to be `TRUE` by default (for simplicity for final users)?

I think that is a great idea!  I don't think it would cause any issues downstream.

**Review by ddsjoberg — CHANGES_REQUESTED** [review]
hey hey, the update looks fantastic! I tried to break it in various ways, and it always performed perfectly.

There is just one thing I am requesting to be changed.  The new columns added `"n"` and `"nevent"` are used in gtsummary already after `add_nevent()`. I know that users go into `.$table_body` and futz with these columns, and it would be helpful to avoid changes that break their code.  What do you think about `"nobs"` and `"nobs_event"` (or anything else really!)?

**Comment by larmarange** [comment]
> There is just one thing I am requesting to be changed. The new columns added `"n"` and `"nevent"` are used in gtsummary already after `add_nevent()`. I know that users go into `.$table_body` and futz with these columns, and it would be helpful to avoid changes that break their code. What do you think about `"nobs"` and `"nobs_event"` (or anything else really!)?

Do you think they could be a confusion between the columns created by `broom.helpers` and those created by `gtsummary::add_nevent()`? Somehow, is it redundant? 

We can change the names in `broom.helpers`. Would maybe prefer `n_obs` and `n_event`.

Regards

**Review by ddsjoberg — APPROVED** [review]
Looks amazing. Love the update

**Pull request merged**
