### PR TITLE
By default, .formula_list_to_named_list() should accept NULL values 

### LINKED ISSUE #137: Potential issue with `formula_list_to_named_list(type_check=)`
In the `gtsummary::tbl_cross()` we accept a digits argument. But rather than the formula-list notation, we accept a single entry that is applied via `tbl_summary()` as `digits = everything() ~ digits`. When I was updating gtsummary to include the `type_check=` argument, I got an error because `digits=` is most often NULL, and the type check doesn't allow `digits = everything() ~ NULL` because it doesn't pass the check.

It was a simple update to code around this, but to continue to allow all previous syntax to continue working I think we should allow NULL values.

Sounds reasonable to you?

``` r
broom.helpers::.formula_list_to_named_list(
  everything() ~ NULL,
  data = gtsummary::trial
)
#> $trt
#> NULL
#> 
#> $age
#> NULL
#> 
#> $marker
#> NULL
#> 
#> $stage
#> NULL
#> 
#> $grade
#> NULL
#> 
#> $response
#> NULL
#> 
#> $death
#> NULL
#> 
#> $ttdeath
#> NULL

broom.helpers::.formula_list_to_named_list(
  everything() ~ NULL,
  data = gtsummary::trial,
  type_check = is.character
)
#> Error: Error processing `` argument for element 'trt'. The value passed is not the expected type/class.
```

<sup>Created on 2021-12-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by larmarange**
for RHS

Option added for not allowing such NULL values

fix #137

### CODE REVIEW

**Comment by ddsjoberg** [comment]
Hi @larmarange , this is a perfect solution, thank you so much!

When I updated this function previously to accept a mix of named lists and formulas, the named lists sections skipped the `.single_formula_to_list()` function, and therefore, the types for named lists were not being checked. I'll push an update to fix the issue.

**Comment by larmarange** [comment]
> I'll push an update to fix the issue.

Thanks. Do not hesitate to push directly in this PR.

**Review by ddsjoberg — APPROVED** [review]
Thanks for preparing this PR!

**Comment by larmarange** [comment]
It has been merged.
 Let me know when a new release will be necessary

**Comment by ddsjoberg** [comment]
Thanks @larmarange ! I think sometime in the new year would be good? 

Is there anything outstanding in gtsummary you want finished before the next gtsummary release?

**Pull request merged**
