### PR TITLE
trying to improve `.assert_package()`

### PR DESCRIPTION
**Pull request by larmarange**
.get_package_dependencies() should be base on packageDescription() as installed.packages() could be time consuming if there are too much installed packages

### CODE REVIEW

**Comment by larmarange** [comment]
Adding `.get_all_packages_dependencies()` to keep a version based on installed.packages()

**Comment by larmarange** [comment]
@ddsjoberg maybe you could have a loot at it

**Comment by larmarange** [comment]
It looks quicker

``` r
library(broom.helpers)
test <- bench::mark(
  a = .get_package_dependencies("broom.helpers"),
  b = .get_all_packages_dependencies("broom.helpers"),
  check = FALSE
)
test
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 a            17.8ms   20.4ms      46.2    5.75MB     23.1
#> 2 b            44.5ms   50.4ms      19.3     4.3MB     28.9
ggplot2::autoplot(test)
```



<sup>Created on 2022-09-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
@larmarange awesome!

do you mind if a take a look in a month or so? I've got so many packages to update with tidyselect changes, and it's my super busy season this month at work.

**Comment by larmarange** [comment]
No pb. There is no emergency

**Comment by larmarange** [comment]
oups ! I have merged the PR while I was thinking updating the PR from the main branch.

**Comment by larmarange** [comment]
However, it does not induce major changes

**Comment by ddsjoberg** [comment]
hey hey @larmarange !

I didn't get a chance to review this (I am sure it's all good!).

But I wanted to let you know that an update to purrr is coming that has a breaking change in broom.helpers. Check out the first line in this issue. https://github.com/tidyverse/purrr/issues/969

The update you just made _may_ have solved this. But it's something we'll need to investigate soon-ish.

**Comment by larmarange** [comment]
Thanks. I will try to explore it

**Comment by larmarange** [comment]
Hi @ddsjoberg Could you have a look at https://github.com/larmarange/broom.helpers/pull/181

It should fix the problem with `purrr`

**Pull request merged**
