### PR TITLE
new `tidy_post_fun` argument in `tidy_plus_plus()`

### LINKED ISSUE #235: Considering a `tidy_post_fun` argument to `tidy_plus_plus()`
The idea is to allow advanced users to pass a custom function to be applied at the end of `tidy_plus_plus()` for customizing the final results.

It could be useful when just basic support is available for a model.

### PR DESCRIPTION
**Pull request by larmarange**
fix #235

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@larmarange I think that can be helpful for users!

Do you think we should pass anything else to `post_fun()`? the model object? that could be helpful, but does make the function a little trickier to specify because it should accept `...` for whatever we choose to pass to it.

**Comment by larmarange** [comment]
At that stage of tidy_plus_plus(), the model is still attached as an attribute of the tibble

**Comment by larmarange** [comment]
So you could use tidy_get_model() if needed

**Comment by ddsjoberg** [comment]
fantastic! looks great!

**Pull request merged**
