### PR TITLE
Support for pairwise contrasts from emmeans

### PR DESCRIPTION
**Pull request by larmarange**
DRAFT

- [x] to be finalised
- [x] update doc
- [x] add test
- [x] update vignette
- [x] update NEWS and README

### CODE REVIEW

**Comment by ddsjoberg** [comment]
hey hey @larmarange !

this all looks great!

I was doing some testing with other types of contrasts. do you think we should document in the help file how various contrasts are handled? for example, if you make a ploy contrast from a factor variable, it is ignored by this new function.

**Comment by larmarange** [comment]
I need to check. I guess that this is not covered by emmeans. But not sure

**Comment by larmarange** [comment]
It seems to work indeed. What was your exact test?

``` r
library(gtsummary)
library(broom.helpers)
#> 
#> Attachement du package : 'broom.helpers'
#> Les objets suivants sont masqués depuis 'package:gtsummary':
#> 
#>     all_continuous, all_contrasts

mod <- glm(
  response ~ stage + grade + trt,
  gtsummary::trial,
  family = binomial,
  contrasts = list(
    stage = contr.sum,
    grade = contr.helmert,
    trt = contr.poly
  )
)


mod |> 
  tbl_regression(exponentiate = TRUE, add_pairwise_contrasts = TRUE) |> 
  as_kable()
```

| **Characteristic**     | **OR** | **95% CI** | **p-value** |
|:-----------------------|:------:|:----------:|:-----------:|
| T Stage                |        |            |             |
| T2 / T1                |  0.61  | 0.20, 1.86 |     0.7     |
| T3 / T1                |  1.10  | 0.35, 3.45 |    \>0.9    |
| T3 / T2                |  1.82  | 0.56, 5.94 |     0.6     |
| T4 / T1                |  0.81  | 0.27, 2.42 |    \>0.9    |
| T4 / T2                |  1.33  | 0.42, 4.18 |    \>0.9    |
| T4 / T3                |  0.73  | 0.23, 2.34 |     0.9     |
| Grade                  |        |            |             |
| II / I                 |  0.96  | 0.39, 2.37 |    \>0.9    |
| III / I                |  1.13  | 0.47, 2.76 |    \>0.9    |
| III / II               |  1.19  | 0.48, 2.95 |     0.9     |
| Chemotherapy Treatment |        |            |             |
| Drug B / Drug A        |  1.24  | 0.67, 2.29 |     0.5     |

<sup>Created on 2022-11-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Review by ddsjoberg — APPROVED** [review]
🦁

**Pull request merged**
