### PR TITLE
better messages when exponentiate is not apppropriate

### PR DESCRIPTION
**Pull request by larmarange**
cf. #197

### CODE REVIEW

**Comment by ddsjoberg** [comment]
Hi @larmarange , this is a super fantastic update. 

Everything looks great. But I did identify one case that does not work. If the tidier has the exponentiate arg AND the default is TRUE AND the user passes `exponentiate = FALSE`, that arg is never passed to the tidier and the returned results are exponentiated.

I think this case is rare, but it could occur for user-defined tidiers where they expect to typically exponentiate the args. I am still trying to think of a way around this edge case..... 🤔 

``` r
library(survival)
library(broom.helpers)
packageVersion("broom.helpers")
#> [1] '1.10.0.9000'

# correctly messages to user that exponentiate arg is ignored
survreg(Surv(time, status) ~ age, lung) |> 
  tidy_plus_plus(exponentiate = TRUE)
#> Warning: The `exponentiate` argument is not supported in the `tidy()` method for
#> `survreg` objects and will be ignored.
#> ! `exponentiate = TRUE` is not valid for this type of model and was ignored.
#> # A tibble: 1 × 19
#>   term  variable var_label var_c…¹ var_t…² var_n…³ contr…⁴ contr…⁵ refer…⁶ label
#>   <chr> <chr>    <chr>     <chr>   <chr>     <int> <chr>   <chr>   <lgl>   <chr>
#> 1 age   age      age       numeric contin…      NA <NA>    <NA>    NA      age  
#> # … with 9 more variables: n_obs <dbl>, n_event <dbl>, exposure <dbl>,
#> #   estimate <dbl>, std.error <dbl>, statistic <dbl>, p.value <dbl>,
#> #   conf.low <dbl>, conf.high <dbl>, and abbreviated variable names ¹​var_class,
#> #   ²​var_type, ³​var_nlevels, ⁴​contrasts, ⁵​contrasts_type, ⁶​reference_row

# checking if a custom tidier for the same class will pass the message too (it does not, which is perfect)
custom_tidy <- function(x, exponentiate = TRUE, ...) {
  df_tidy <- broom::tidy(x, ...)
  
  if (isTRUE(exponentiate)) {
    df_tidy <-
      df_tidy |> 
      dplyr::mutate(
        dplyr::across(.cols = c("estimate", "conf.low", "conf.high"), .fns = exp)
      )
  }
  
  df_tidy
}

# if the default in a custom tidier is exponentiate = TRUE, AND a user passes exponentiate = FALSE, it is not passed to the tidier. 
survreg(Surv(time, status) ~ age, lung) |> 
  tidy_plus_plus(exponentiate = FALSE, tidy_fun = custom_tidy) |> 
  dplyr::select(term, estimate, conf.low, conf.high)
#> # A tibble: 1 × 4
#>   term  estimate conf.low conf.high
#>   <chr>    <dbl>    <dbl>     <dbl>
#> 1 age      0.986    0.973      1.00
```

<sup>Created on 2022-12-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by larmarange** [comment]
OK. Thanks for the flag. I have updated the code. `exponentiate = FALSE` is now passed (default value as expected).
There is no message but the results are consistent.

**Comment by larmarange** [comment]
Let me know if if it ok for you @ddsjoberg 

I'm also planning a new release of `broom.helpers` as I would like to use some new functions in January with my students

**Review by ddsjoberg — APPROVED** [review]
updates look super SUPER fantastic!

**Pull request merged**
