### PR TITLE
Adding variable type selectors

### PR DESCRIPTION
**Pull request by ddsjoberg**
This is the first draft.  I need to review further before putting it up for review

NEED TO ADD UNIT TESTS

Question: Should these be updated to account for `continuous2` variable types, or should I just re0implement in gtsummary?

``` r
library(broom.helpers)

lm(mpg ~ hp * factor(cyl), mtcars) %>%
  tidy_and_attach() %>%
  tidy_identify_variables() %>%
  tidy_add_reference_rows() %>%
  tidy_add_header_rows() %>%
  tidy_select_variables(include = c(all_interaction(), all_continuous()))
#> # A tibble: 5 x 13
#>   term  variable var_label var_class var_type header_row contrasts reference_row
#>   <chr> <chr>    <chr>     <chr>     <chr>    <lgl>      <chr>     <lgl>        
#> 1 (Int~ <NA>     (Interce~ <NA>      interce~ NA         <NA>      NA           
#> 2 hp    hp       hp        numeric   continu~ NA         <NA>      NA           
#> 3 <NA>  hp:fact~ hp * fac~ <NA>      interac~ TRUE       <NA>      NA           
#> 4 hp:f~ hp:fact~ hp * fac~ <NA>      interac~ FALSE      <NA>      NA           
#> 5 hp:f~ hp:fact~ hp * fac~ <NA>      interac~ FALSE      <NA>      NA           
#> # ... with 5 more variables: label <chr>, estimate <dbl>, std.error <dbl>,
#> #   statistic <dbl>, p.value <dbl>
```

<sup>Created on 2020-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by larmarange** [comment]
Dear @ddsjoberg 

thanks for this first draft. 

As I understood "continuous2" is a specific type for `tbl_summarry()` as it depends on the number of statistics displayed in the table. Therefore, it does not seem relevant for broom.helpers

Just to be sure, for your code to work, I need to implement that proposition: for dichotomous variables, replace the value"categorical" by "dichotomous" in tidy_identify_variable()?

**Comment by larmarange** [comment]
By the way, to identify dichotomous variables, I will have to count the number of levels for categorical variables. Do you think it would be relevant to store it in a new column "var_nlevels" in case it could be useful somewhere else?

**Comment by larmarange** [comment]
As a reminder, to count the number of levels

```r
nlevels <- model_get_xlevels(model) %>% lapply(length)
nlevels <- dplyr::tibble(variable = names(nlevels), nlevels = unlist(nlevels))
```

Code to be integrated in `model_identify_variables()`

**Comment by larmarange** [comment]
For your information, I have added in master branch a `var_nlevels` column and `var_type` is now equal to `"dichotomous"` for these variables

**Comment by ddsjoberg** [comment]
1. YES! I love the addition `var_nlevels` and `"dichotomous"`.

1. You're correct, `"continuous2"` is only for `tbl_summary()`.  I was hoping I could think of a way to implement the `all_*()` select helpers in a way where they could simply be imported into gtsummary.....but I think I won't import them and I'll re-implement something similar that will work with all the gtsummary tables types.

1. I'll finish up this PR and mark it ready for review (hopefully tonight!).

**Comment by ddsjoberg** [comment]
@larmarange this is ready for your review

**Review by larmarange — APPROVED** [review]
Can you add tests for `dichotomous = TRUE` for `all_categorical()`?

And a NEWS entry.

If you don't have time, I will do next week

**Comment by larmarange** [comment]
We will have to check that these selecters will work properly when both brool.helpers and gtdummay are loader

**Comment by ddsjoberg** [comment]
> Can you add tests for `dichotomous = TRUE` for `all_categorical()`?
> 
> And a NEWS entry.

Both added!

> We will have to check that these selecters will work properly when both brool.helpers and gtdummay are loader

There is a name conflict with these functions and the gtsummary functions, and if both are loaded one of the package's version of the functions will be masked (aka will not work properly). I _may_ be able to make some internal gtsummary updates to work with the structure here in broom.helpers. But it's not a priority now.

**Comment by larmarange** [comment]
Thanks a lot !!!  Will merge it tonight or tomorrow.

It would be important to avoid conflict, but rather to import the helpers in `gtsummary` as we want to be able to use functions such as `all_categorical()` both for `tbl_summary()` and for `tbl_regression()`

Just a quick comment: if I understood properly, in this PR you create in an environment `env_variable_type` and you check `env_variable_type$lst_variable_types`. 

In `gtsummary`, you create `meta_data_env` and you check `meta_data_env$summary_type`. Except that, the code is identical.

Maybe an option would be:

- for `tbl_summary` create `env_variable_type$lst_variable_types` instead of `meta_data_env$summary_type`
- therefore, you could import from `broom.helpers` the functions `all_categorical()`, `all_continuous` etc. It should in that case work in both context, with no conflict
- the trick is the creation of `env_variable_type$lst_variable_types` which is managed diffently in both package

Bonus question: do you think we should adopt the same strategy for `all_double()`, `all_factor()` etc. ? If we want to allow users to use it in both `tbl_regression()` and `tbl_summary` (knowing that `tbl_regression()` partially rely on `broom.helpers`) we could want to implement it in `broom.helpers` and to import them in `gtsummary`.

What do you think?

**Comment by larmarange** [comment]
Note to myself: after merge, add examples of use in the vignette and the document of `tidy_` functions using select helpers. Ensure proper links within doc.

**Pull request merged**
