### PR TITLE
3.4 Workflow

### PR DESCRIPTION
**Pull request by ddsjoberg**
Ooops, the 3.4 checks failed still.  I'll keep the PR as a draft until I get the 3.4 checks are sorted out!

### CODE REVIEW

**Comment by larmarange** [comment]
The problem is that some packages (gam, geepack...) are not available for 3.4.0

**Comment by larmarange** [comment]
I have added `skip_if(packageVersion("geepack") < 1.3)` in the tests (as dietox was not avalaible in old versions of geepack). I guess it could help

**Comment by ddsjoberg** [comment]
> I have added `skip_if(packageVersion("geepack") < 1.3)` in the tests (as dietox was not avalaible in old versions of geepack). I guess it could help

Sorry for this hassle. Should I add back the 3.4 checks now that you added the geepack conditional checking?

**Comment by larmarange** [comment]
> Sorry for this hassle. Should I add back the 3.4 checks now that you added the geepack conditional checking?

Yes please

**Comment by ddsjoberg** [comment]
oy! I think this should be good to go.  These historic checks are tricky. I need to make the same updates on gtsummary.

**Comment by larmarange** [comment]
Thanks to you

**Comment by ddsjoberg** [comment]
Thanks for your patience on this one 😜😳

**Pull request merged**
