### PR TITLE
support for `multgee` and use of `lintr`

### LINKED ISSUE #185: Support for multinomial GEE regression models
Today, I stackoverflow user was asking about support for `multgee::nomLORgee()` models. We can keep this open as a record for when we get to it.

```r
library(multgee)
data(housing)   
fitmod <- nomLORgee(y ~ factor(time) * sec, data = housing, id = id, repeated = time)
```

https://stackoverflow.com/questions/73997977

### LINKED ISSUE #187: Lint package

### PR DESCRIPTION
**Pull request by larmarange**
fix #185
fix #187 

- [x] identify type of coef
- [x] lint code
- [x] finalize
- [x] add tests
- [x] update doc
- [x] update news

### CODE REVIEW

**Comment by larmarange** [comment]
Dear @ddsjoberg 

I have also cleaned the code of the package by using `lintr`. I will realize that it may complexify the review as everything is in the same PR. I'm truly sorry (when I realized it, it was too late).

**Comment by ddsjoberg** [comment]
@larmarange FYI, I am SUPER busy at work for the rest of the month (abstract deadlines!). I can get to this in a couple of weeks. Hope that is ok!

**Comment by larmarange** [comment]
@ddsjoberg no worries, I understand

Release date of `purrr` 1.0.0 has not been given yet.

It would be good to embed this PR in the next release of `broom.helpers`

**Review by ddsjoberg — APPROVED** [review]
hey hey @larmarange ! I tried various options with the new model type, and everything works! The linting is pretty great too!

**Pull request merged**
